"""Cuarta Migración

Revision ID: 2a4cf6ad8f45
Revises: c57a7adfbc5a
Create Date: 2025-11-04 17:41:19.418375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a4cf6ad8f45'
down_revision: Union[str, Sequence[str], None] = 'c57a7adfbc5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
