"""Segunda Migracion: Modelos con Relaciones

Revision ID: 5f68d0726a37
Revises: df46c9f3cbdd
Create Date: 2025-11-03 11:54:20.834247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f68d0726a37'
down_revision: Union[str, Sequence[str], None] = 'df46c9f3cbdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profesores', sa.Column('departamento_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'profesores', 'departamentos', ['departamento_id'], ['id_departamento'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profesores', type_='foreignkey')
    op.drop_column('profesores', 'departamento_id')
    # ### end Alembic commands ###
