"""Séptima Migración

Revision ID: 7e4e130b2cab
Revises: 99e98cde8904
Create Date: 2025-11-05 23:12:45.947506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e4e130b2cab'
down_revision: Union[str, Sequence[str], None] = '99e98cde8904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumnos', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('alumnos', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('alumnos', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('alumnos', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('departamentos', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('departamentos', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('departamentos', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('departamentos', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('profesores', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('profesores', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('profesores', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('profesores', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profesores', 'updated_at')
    op.drop_column('profesores', 'created_at')
    op.drop_column('profesores', 'deleted_at')
    op.drop_column('profesores', 'is_deleted')
    op.drop_column('departamentos', 'updated_at')
    op.drop_column('departamentos', 'created_at')
    op.drop_column('departamentos', 'deleted_at')
    op.drop_column('departamentos', 'is_deleted')
    op.drop_column('alumnos', 'updated_at')
    op.drop_column('alumnos', 'created_at')
    op.drop_column('alumnos', 'deleted_at')
    op.drop_column('alumnos', 'is_deleted')
    # ### end Alembic commands ###
