"""Sexta Migración

Revision ID: 99e98cde8904
Revises: faa2eae98506
Create Date: 2025-11-05 22:12:28.769000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99e98cde8904'
down_revision: Union[str, Sequence[str], None] = 'faa2eae98506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('alumnos_password_key'), 'alumnos', type_='unique')
    op.drop_column('alumnos', 'password')
    op.drop_constraint(op.f('departamentos_password_key'), 'departamentos', type_='unique')
    op.drop_column('departamentos', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departamentos', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('departamentos_password_key'), 'departamentos', ['password'], postgresql_nulls_not_distinct=False)
    op.add_column('alumnos', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('alumnos_password_key'), 'alumnos', ['password'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
