"""Tercera Migracion

Revision ID: c57a7adfbc5a
Revises: 5f68d0726a37
Create Date: 2025-11-04 17:18:56.022310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c57a7adfbc5a'
down_revision: Union[str, Sequence[str], None] = '5f68d0726a37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profesores', 'departamento_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profesores', 'departamento_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
