"""Primera Migracion: Modelos sin Relaciones

Revision ID: df46c9f3cbdd
Revises: 
Create Date: 2025-11-02 18:38:49.399898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df46c9f3cbdd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumnos',
    sa.Column('id_alumno', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('facultad', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_alumno'),
    sa.UniqueConstraint('password')
    )
    op.create_index(op.f('ix_alumnos_email'), 'alumnos', ['email'], unique=True)
    op.create_index(op.f('ix_alumnos_id_alumno'), 'alumnos', ['id_alumno'], unique=False)
    op.create_table('departamentos',
    sa.Column('id_departamento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_departamento'),
    sa.UniqueConstraint('password')
    )
    op.create_index(op.f('ix_departamentos_id_departamento'), 'departamentos', ['id_departamento'], unique=False)
    op.create_index(op.f('ix_departamentos_nombre'), 'departamentos', ['nombre'], unique=True)
    op.create_table('profesores',
    sa.Column('id_profesor', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('asignatura', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_profesor'),
    sa.UniqueConstraint('password')
    )
    op.create_index(op.f('ix_profesores_email'), 'profesores', ['email'], unique=True)
    op.create_index(op.f('ix_profesores_id_profesor'), 'profesores', ['id_profesor'], unique=False)
    op.create_table('profesor-alumno',
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id_alumno'], ),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesores.id_profesor'], ),
    sa.PrimaryKeyConstraint('profesor_id', 'alumno_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profesor-alumno')
    op.drop_index(op.f('ix_profesores_id_profesor'), table_name='profesores')
    op.drop_index(op.f('ix_profesores_email'), table_name='profesores')
    op.drop_table('profesores')
    op.drop_index(op.f('ix_departamentos_nombre'), table_name='departamentos')
    op.drop_index(op.f('ix_departamentos_id_departamento'), table_name='departamentos')
    op.drop_table('departamentos')
    op.drop_index(op.f('ix_alumnos_id_alumno'), table_name='alumnos')
    op.drop_index(op.f('ix_alumnos_email'), table_name='alumnos')
    op.drop_table('alumnos')
    # ### end Alembic commands ###
