"""Quinta Migracion

Revision ID: faa2eae98506
Revises: 2a4cf6ad8f45
Create Date: 2025-11-04 19:55:42.744014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa2eae98506'
down_revision: Union[str, Sequence[str], None] = '2a4cf6ad8f45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profesor_alumno',
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id_alumno'], ),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesores.id_profesor'], ),
    sa.PrimaryKeyConstraint('profesor_id', 'alumno_id')
    )
    op.drop_table('profesor-alumno')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profesor-alumno',
    sa.Column('profesor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('alumno_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id_alumno'], name=op.f('profesor-alumno_alumno_id_fkey')),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesores.id_profesor'], name=op.f('profesor-alumno_profesor_id_fkey')),
    sa.PrimaryKeyConstraint('profesor_id', 'alumno_id', name=op.f('profesor-alumno_pkey'))
    )
    op.drop_table('profesor_alumno')
    # ### end Alembic commands ###
